test jobs

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -346,100 +346,100 @@ jobs:
       - revert-migrations
       - destroy-environment     
                     
-  deploy-backend:
-    docker:
-      # Docker image here that supports Ansible
-      - image: cimg/python:3.7-node
-    steps:
-      # Checkout code from git
-      - checkout       
-      # Add ssh keys with fingerprint
-      - add_ssh_keys:
-          fingerprints: ["8d:3e:53:3f:96:70:3d:53:80:e4:eb:08:23:19:9e:8f"]
-      # attach workspace
-      - attach_workspace:
-          at: ~/
+#   deploy-backend:
+#     docker:
+#       # Docker image here that supports Ansible
+#       - image: cimg/python:3.7-node
+#     steps:
+#       # Checkout code from git
+#       - checkout       
+#       # Add ssh keys with fingerprint
+#       - add_ssh_keys:
+#           fingerprints: ["8d:3e:53:3f:96:70:3d:53:80:e4:eb:08:23:19:9e:8f"]
+#       # attach workspace
+#       - attach_workspace:
+#           at: ~/
 
-      - run:
-          name: Install aws dependencies
-          command: |
-            curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
-            unzip awscliv2.zip
-            sudo ./aws/install
-      - run:
-          name: Install Ansible
-          command: |
-            sudo apt update
-            sudo apt install software-properties-common -y
-            sudo add-apt-repository --yes --update ppa:ansible/ansible
-            sudo apt install ansible -y
-#              pip install --upgrade
-      - run:
-          name: Deploy backend
-          command: |
-            # your code here
-            cd backend # echo TYPEORM_HOST=$TYPEORM_HOST >> "backend/.env"
-            npm i
-            npm run build
-            cd ..
-            # Zip the directory
-            tar -C backend -czvf artifact.tar.gz .
-            mkdir -p ~/project/.circleci/ansible/roles/deploy/files/
-            mv artifact.tar.gz .circleci/ansible/roles/deploy/files/artifact.tar.gz
-            cd .circleci/ansible
-            echo "Contents  of the inventory.txt file is -------"
-            cat inventory.txt
-            ansible-playbook -i inventory.txt deploy-backend.yml -v
-      # Here's where you will add some code to rollback on failure  
-      - revert-migrations
-      - destroy-environment     
+#       - run:
+#           name: Install aws dependencies
+#           command: |
+#             curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
+#             unzip awscliv2.zip
+#             sudo ./aws/install
+#       - run:
+#           name: Install Ansible
+#           command: |
+#             sudo apt update
+#             sudo apt install software-properties-common -y
+#             sudo add-apt-repository --yes --update ppa:ansible/ansible
+#             sudo apt install ansible -y
+# #              pip install --upgrade
+#       - run:
+#           name: Deploy backend
+#           command: |
+#             # your code here
+#             cd backend # echo TYPEORM_HOST=$TYPEORM_HOST >> "backend/.env"
+#             npm i
+#             npm run build
+#             cd ..
+#             # Zip the directory
+#             tar -C backend -czvf artifact.tar.gz .
+#             mkdir -p ~/project/.circleci/ansible/roles/deploy/files/
+#             mv artifact.tar.gz .circleci/ansible/roles/deploy/files/artifact.tar.gz
+#             cd .circleci/ansible
+#             echo "Contents  of the inventory.txt file is -------"
+#             cat inventory.txt
+#             ansible-playbook -i inventory.txt deploy-backend.yml -v
+#       # Here's where you will add some code to rollback on failure  
+#       - revert-migrations
+#       - destroy-environment     
 
-  smoke-test:
-    docker:
-      - image: cimg/node:13.8.0
-    steps:
-      # - run:
-      #     name: Install dependencies
-      #     command: |
-      #       yum -y install jq tar gzip git curl
-      # - install_awscli
-      - run:
-          name: Install AWS CLI 
-          command: |
-            curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
-            unzip awscliv2.zip
-            sudo ./aws/install
-            # sudo ./aws/install -i /usr/local/aws-cli -b /usr/local/bin
+#   smoke-test:
+#     docker:
+#       - image: cimg/node:13.8.0
+#     steps:
+#       # - run:
+#       #     name: Install dependencies
+#       #     command: |
+#       #       yum -y install jq tar gzip git curl
+#       # - install_awscli
+#       - run:
+#           name: Install AWS CLI 
+#           command: |
+#             curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
+#             unzip awscliv2.zip
+#             sudo ./aws/install
+#             # sudo ./aws/install -i /usr/local/aws-cli -b /usr/local/bin
 
-      - run:
-          name: Backend smoke test.
-          command: |
-            export BACKEND_PUBLIC_IP=$(aws --region us-west-2 ec2 describe-instances --filters "Name=tag:Name,Values=backend-${CIRCLE_WORKFLOW_ID:0:7}" --query 'Reservations[*].Instances[*].PublicDnsName' --output text)
-            export API_URL="http://${BACKEND_PUBLIC_IP}:3030"
-            echo "${API_URL}"  #   curl -s ${API_URL}/api/status -v 
-            if curl -s ${API_URL}/api/status | grep "ok"
-            then
-              exit 0
-            else
-              exit 1
-            fi       
+#       - run:
+#           name: Backend smoke test.
+#           command: |
+#             export BACKEND_PUBLIC_IP=$(aws --region us-west-2 ec2 describe-instances --filters "Name=tag:Name,Values=backend-${CIRCLE_WORKFLOW_ID:0:7}" --query 'Reservations[*].Instances[*].PublicDnsName' --output text)
+#             export API_URL="http://${BACKEND_PUBLIC_IP}:3030"
+#             echo "${API_URL}"  #   curl -s ${API_URL}/api/status -v 
+#             if curl -s ${API_URL}/api/status | grep "ok"
+#             then
+#               exit 0
+#             else
+#               exit 1
+#             fi       
 
-      - run:
-          name: Frontend smoke test.
-          command: |
-            URL="http://udapeople-${CIRCLE_WORKFLOW_ID:0:7}.s3-website-us-west-2.amazonaws.com/#/employees"            
-            echo ${URL} 
-            if curl -s ${URL} | grep "Welcome"
-            then
-                # Change this to 0 after the job fails
-              exit 0
-            else
-              exit 1
-            fi
+#       - run:
+#           name: Frontend smoke test.
+#           command: |
+#             URL="http://udapeople-${CIRCLE_WORKFLOW_ID:0:7}.s3-website-us-west-2.amazonaws.com/#/employees"            
+#             echo ${URL} 
+#             if curl -s ${URL} | grep "Welcome"
+#             then
+#                 # Change this to 0 after the job fails
+#               exit 0
+#             else
+#               exit 1
+#             fi
 
    
-      - destroy-environment  
-      - revert-migrations
+#       - destroy-environment  
+#       - revert-migrations
       
 
 
@@ -467,12 +467,12 @@ workflows:
       #     requires: [deploy-infrastructure]
 
       - run-migrations:
-           requires: [configure-infrastructure]
+          requires: [configure-infrastructure]
       - deploy-frontend:
-           requires: [run-migrations]
-      - deploy-backend:
           requires: [run-migrations]
-      - smoke-test:
-          requires: [deploy-backend, deploy-frontend]
+      # - deploy-backend:
+      #     requires: [run-migrations]
+      # - smoke-test:
+      #     requires: [deploy-backend, deploy-frontend]
 
           
